[package]
name = "fuzz_from_str"
version = "0.1.0"
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
rand = "0.8.5"
libfuzzer-sys = "0.4"
regex = "1.8.3"
time = "0.3.21"

[dependencies.humantime_to_duration]
path = "../"

[[bin]]
name = "fuzz_from_str"
path = "fuzz_targets/from_str.rs"
test = false
doc = false
